# Generated by Django 2.2.4 on 2020-11-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beltReviewApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_name',
            new_name='email',
        ),
    ]
