# Generated by Django 2.2.4 on 2020-11-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltReviewApp', '0003_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
