# Generated by Django 2.2.4 on 2020-11-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltReviewApp', '0004_auto_20201112_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
