# Generated by Django 2.2.4 on 2020-11-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beltReviewApp', '0006_favorite_otherlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite',
            new_name='WishList',
        ),
    ]
