# Generated by Django 2.2.4 on 2020-11-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltReviewApp', '0007_auto_20201113_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='userId',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
