# Generated by Django 2.2.4 on 2020-11-13 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beltReviewApp', '0008_wishlist_userid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WishList',
            new_name='Item',
        ),
        migrations.DeleteModel(
            name='OtherList',
        ),
    ]
