# Generated by Django 2.2.4 on 2020-11-15 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltPracticeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=12345678, max_length=255),
            preserve_default=False,
        ),
    ]
