# Generated by Django 2.2.4 on 2020-11-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltPracticeApp', '0003_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='decription',
            field=models.TextField(default='A good movie'),
        ),
    ]
