# Generated by Django 2.2.4 on 2020-11-15 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beltPracticeApp', '0004_movie_decription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='decription',
            new_name='description',
        ),
    ]
