# Generated by Django 2.2.4 on 2020-11-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksAndAuthorsApp', '0002_authors_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='Author notes'),
        ),
    ]
