# Generated by Django 2.2.4 on 2020-11-08 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksAndAuthorsApp', '0003_auto_20201108_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='notes',
        ),
    ]
