# Generated by Django 2.2.4 on 2020-11-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksAndAuthorsApp', '0005_authors_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='allBooks',
            field=models.ManyToManyField(related_name='books', to='booksAndAuthorsApp.Books'),
        ),
    ]
