# Generated by Django 2.2.4 on 2020-11-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksAndAuthorsApp', '0006_authors_allbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='allBooks',
            field=models.ManyToManyField(related_name='authors', to='booksAndAuthorsApp.Books'),
        ),
    ]
