# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2021-10-18 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='comments',
        ),
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
