# Generated by Django 2.2.4 on 2020-11-07 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojoNinjasApp', '0003_auto_20201106_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ninja',
            name='dojo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ninjas', to='dojoNinjasApp.Dojo'),
        ),
    ]
