# Generated by Django 2.2.4 on 2020-11-07 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojoNinjasApp', '0004_auto_20201107_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='dojo',
            new_name='dojo_ninjas',
        ),
    ]
