# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2021-10-14 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_ninja_dojo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='No Description', max_length=500),
            preserve_default=False,
        ),
    ]
