# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f225726a5b3c80aeb2f9b6973f0430787be5012a3931b5c92bfdeb86da68d34652304e2274a3c2cd6e622637f7157bcc58dc16cc0117df7ec3673d0fb6ba62c

test:
  secret_key_base: 5ad915e49b12e8cde7ab59998a7772eff38b2739286db661b5d882d096224887c2584a0d1de60b1348eaa051d1102531cb72613179e3ee95211ca813c741c9d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
